name: Apollo Schema Check

# Generally running a pull_request_target with secrets from the fork is risky, however we are only using the schema.graphql
# file and not executing any code from the branch so it's safe here.
on:
  pull_request_target:
    branches:
      - main

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Subgraph Check
        uses: iansu/apollo-schema-check-action@v2
        with:
          title: Metadata API
          graph: infratographer
          variant: main
          localSchemaFile: schema.graphql
          serviceName: metadata-api
          validationPeriod: P2W
          key: ${{ secrets.APOLLO_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
          APOLLO_VCS_BRANCH: ${{ github.event.pull_request.head.label }}
